### ISSUE TITLE
Can I read in elements from the file

### ISSUE THREAD

**Issue by githubvipuser** [garawalid/LH-BloomFilter#1]
Can I save the read filter elements to a file?
All elements are then read from the file

**Comment by garawalid** [comment]
@githubvipuser It's possible to save and load it as binary file in `.npy` format.
I'll add this feature ASAP. 
 
Btw, It's a good idea, thanks!

**Comment by garawalid** [comment]
@githubvipuser 
Now it's possible to save and load bloom filter. You just need to install the latest version (v0.0.5)

```python
# Save bloom filter as a binary file in npy format
bf.save('bf.npy')

# Load bloom filter from a file 
bf3 = BloomFilter().load('bf.npy')

```

**Comment by githubvipuser** [comment]
@garawalid
Thank you for everything.
 I have a collection of elements, The size is 2gb.
So I should set m= 2,147,483,648 or m=2,147,483,648/8?

**Comment by garawalid** [comment]
@githubvipuser 
Good question. The size of the bloom filter (`m`) depends on the number of unique elements that it will process. So you have to know how much unique elements you have in your data. 

Also, the size of `m` and the number of hash functions `k` will affect the false positive rate. Right now there is no formula how to pick the right parameter, it stills an approximation. 

I invite you to learn more about the framework in [this paper](https://arxiv.org/pdf/1804.04777.pdf)  part II.A

**Comment by githubvipuser** [comment]
@garawalid
I thought it was by the total bytes or bits of the element.
